name: Setup
description: Common setup steps

inputs:
  shell:
    description: The Nix flake shell
    required: true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

    - name: Cache Nix
      uses: nix-community/cache-nix-action@b426b118b6dc86d6952988d396aa7c6b09776d08 # v7
      with:
        primary-key: nix-${{ inputs.shell }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ inputs.shell }}-${{ runner.os }}-${{ runner.arch }}-
        purge: true
        purge-prefixes: nix-${{ inputs.shell }}-${{ runner.os }}-${{ runner.arch }}-
        purge-created: 86400

    - name: Configure SCCache
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

    - name: Initialize Nix shell
      env:
        NIX_SHELL: ${{ inputs.shell }}
      shell: bash
      run: nix develop ".#${NIX_SHELL}"
