name: Setup
description: Common setup steps

inputs:
  shell:
    description: The Nix flake shell
    required: true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30

    - name: Cache Nix
      uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
      with:
        primary-key: nix-${{ inputs.shell }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ inputs.shell }}-${{ runner.os }}-${{ runner.arch }}-

    - name: Configure SCCache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

    - name: Initialize Nix shell
      env:
        NIX_SHELL: ${{ inputs.shell }}
      shell: bash
      run: nix develop ".#${NIX_SHELL}"
