name: Setup
description: Common setup steps

inputs:
  shell:
    description: The Nix flake shell
    required: true

  cachix-auth-token:
    description: The secret Cachix token
    required: true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v14

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: dusksystems
        authToken: ${{ inputs.cachix-auth-token }}
        extraPullNames: nix-community

    - name: Configure SCCache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

    - name: Initialize Nix shell
      env:
        NIX_SHELL: ${{ inputs.shell }}
      shell: bash
      run: nix develop ".#${NIX_SHELL}"
