name: Setup
description: Common setup steps

runs:
  using: composite
  steps:
    - name: Host info
      shell: bash
      run: |
        uname --all
        cat /proc/cpuinfo

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

    - name: Cache Nix
      uses: DuskSystems/nix-cache-action@dfb0f60031b8762e2211da4c65f3da96e5a8727e # v1.4.1
      with:
        key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/flake.lock', '**/*.nix') }}
        restore-keys: |
          nix-${{ runner.os }}-${{ runner.arch }}-

    - name: Configure SCCache
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

    - name: Build shells
      shell: bash
      run: |
        for shell in $(nix flake show --json | jq -r '.devShells | to_entries[0].value | keys[] | select(startswith("ci"))'); do
          nix develop ".#${shell}" --command true
        done
