name: Setup
description: Common setup steps

inputs:
  shell:
    required: true
    description: Which Nix dev shell to use.

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v16
      with:
        determinate: true

    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Configure SCCache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

    - name: Initialize Nix shell
      shell: bash
      run: nix develop .#${{ inputs.shell }}
