[toolchain]
# FIXME: Once 1.81 releases, switch back to stable.
channel = "nightly-2024-08-04"
targets = ["wasm32-unknown-unknown"]
components = [
  "cargo",
  "rustfmt",
  "clippy",
  "rust-src",
  "rust-std",
  "rust-analyzer",
]
