# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "1.80.1"
profile = "minimal"
components = [
  "clippy",
  "llvm-tools",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rustfmt",
]
