# https://doc.rust-lang.org/cargo/reference/config.html

# https://doc.rust-lang.org/cargo/reference/unstable.html
[unstable]
codegen-backend = true
feature-unification = true
profile-hint-mostly-unused = true

# https://doc.rust-lang.org/cargo/reference/resolver.html
[resolver]
feature-unification = "workspace"

# https://doc.rust-lang.org/cargo/reference/profiles.html#dev
[profile.dev]
debug = "line-tables-only"
hint-mostly-unused = true
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false

[profile.dev.build-override]
opt-level = 3

# https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.release]
hint-mostly-unused = true
overflow-checks = true

# https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles
[profile.profiling]
inherits = "release"
debug = true
