#[must_use]
pub fn paths() -> impl IntoIterator<Item = &'static str> {
    vec![
        "/app",
        "/app-manifests/0/conversions",
        "/app/installations",
        "/app/installations/12345",
        "/app/installations/12345/access_tokens",
        "/applications/67890/grants/777cc25bacbd7cd4f4ddd631006a998fa74b5ed3",
        "/applications/67890/tokens/777cc25bacbd7cd4f4ddd631006a998fa74b5ed3",
        "/applications/grants",
        "/applications/grants/1",
        "/apps/rust-lang",
        "/authorizations",
        "/authorizations/144",
        "/authorizations/clients/67890",
        "/authorizations/clients/67890/233",
        "/codes_of_conduct",
        "/codes_of_conduct/377",
        "/content_references/610/attachments",
        "/emojis",
        "/events",
        "/feeds",
        "/gists",
        "/gists/public",
        "/gists/starred",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/comments",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/comments/2274119",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/commits",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/forks",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/star",
        "/gists/7c220d4d6d95b389816bc9d3fbb7a5d4/2aa4c46cfdd726e97360c2734835aa3515e8c858",
        "/gitignore/templates",
        "/gitignore/templates/rust",
        "/installation/repositories",
        "/issues",
        "/legacy/issues/search/rust-lang/rust/987/1597",
        "/legacy/repos/search/1597",
        "/legacy/user/email/rust%40rust-lang.org",
        "/legacy/user/search/1597",
        "/licenses",
        "/licenses/mit",
        "/markdown",
        "/markdown/raw",
        "/marketplace_listing/accounts/rust-lang",
        "/marketplace_listing/plans",
        "/marketplace_listing/plans/987/accounts",
        "/marketplace_listing/stubbed/accounts/rust-lang",
        "/marketplace_listing/stubbed/plans",
        "/marketplace_listing/stubbed/plans/987/accounts",
        "/meta",
        "/networks/rust-lang/rust/events",
        "/notifications",
        "/notifications/threads/233",
        "/notifications/threads/233/subscription",
        "/organizations",
        "/orgs/rust-lang",
        "/orgs/rust-lang/blocks",
        "/orgs/rust-lang/blocks/alexcrichton",
        "/orgs/rust-lang/events",
        "/orgs/rust-lang/hooks",
        "/orgs/rust-lang/hooks/1357908642",
        "/orgs/rust-lang/hooks/1357908642/pings",
        "/orgs/rust-lang/installation",
        "/orgs/rust-lang/interaction-limits",
        "/orgs/rust-lang/invitations",
        "/orgs/rust-lang/invitations/c9f8304351ad4223e4f618e9a329b2b94776b25e/teams",
        "/orgs/rust-lang/issues",
        "/orgs/rust-lang/members",
        "/orgs/rust-lang/members/alexcrichton",
        "/orgs/rust-lang/memberships/alexcrichton",
        "/orgs/rust-lang/migrations",
        "/orgs/rust-lang/migrations/233",
        "/orgs/rust-lang/migrations/233/archive",
        "/orgs/rust-lang/migrations/233/repos/rust/lock",
        "/orgs/rust-lang/outside_collaborators",
        "/orgs/rust-lang/outside_collaborators/alexcrichton",
        "/orgs/rust-lang/projects",
        "/orgs/rust-lang/public_members",
        "/orgs/rust-lang/public_members/alexcrichton",
        "/orgs/rust-lang/repos",
        "/orgs/rust-lang/teams",
    ]
}

#[macro_export]
macro_rules! routes {
    (colon) => {{
        routes!(finish => ":p1", ":p2", ":p3", ":p4")
    }};

    (brackets) => {{
        routes!(finish => "{p1}", "{p2}", "{p3}", "{p4}")
    }};

    (finish => $p1:literal, $p2:literal, $p3:literal, $p4:literal) => {{
        [
            concat!("/app"),
            concat!("/app-manifests/", $p1, "/conversions"),
            concat!("/app/installations"),
            concat!("/app/installations/", $p1),
            concat!("/app/installations/", $p1, "/access_tokens"),
            concat!("/applications/", $p1, "/grants/", $p2),
            concat!("/applications/", $p1, "/tokens/", $p2),
            concat!("/applications/grants"),
            concat!("/applications/grants/", $p1),
            concat!("/apps/", $p1),
            concat!("/authorizations"),
            concat!("/authorizations/", $p1),
            concat!("/authorizations/clients/", $p1),
            concat!("/authorizations/clients/", $p1, "/", $p2),
            concat!("/codes_of_conduct"),
            concat!("/codes_of_conduct/", $p1),
            concat!("/content_references/", $p1, "/attachments"),
            concat!("/emojis"),
            concat!("/events"),
            concat!("/feeds"),
            concat!("/gists"),
            concat!("/gists/public"),
            concat!("/gists/starred"),
            concat!("/gists/", $p1),
            concat!("/gists/", $p1, "/comments"),
            concat!("/gists/", $p1, "/comments/", $p2),
            concat!("/gists/", $p1, "/commits"),
            concat!("/gists/", $p1, "/forks"),
            concat!("/gists/", $p1, "/star"),
            concat!("/gists/", $p1, "/", $p2),
            concat!("/gitignore/templates"),
            concat!("/gitignore/templates/", $p1),
            concat!("/installation/repositories"),
            concat!("/issues"),
            concat!("/legacy/issues/search/", $p1, "/", $p2, "/", $p3, "/", $p4),
            concat!("/legacy/repos/search/", $p1),
            concat!("/legacy/user/email/", $p1),
            concat!("/legacy/user/search/", $p1),
            concat!("/licenses"),
            concat!("/licenses/", $p1),
            concat!("/markdown"),
            concat!("/markdown/raw"),
            concat!("/marketplace_listing/accounts/", $p1),
            concat!("/marketplace_listing/plans"),
            concat!("/marketplace_listing/plans/", $p1, "/accounts"),
            concat!("/marketplace_listing/stubbed/accounts/", $p1),
            concat!("/marketplace_listing/stubbed/plans"),
            concat!("/marketplace_listing/stubbed/plans/", $p1, "/accounts"),
            concat!("/meta"),
            concat!("/networks/", $p1, "/", $p2, "/events"),
            concat!("/notifications"),
            concat!("/notifications/threads/", $p1),
            concat!("/notifications/threads/", $p1, "/subscription"),
            concat!("/organizations"),
            concat!("/orgs/", $p1),
            concat!("/orgs/", $p1, "/blocks"),
            concat!("/orgs/", $p1, "/blocks/", $p2),
            concat!("/orgs/", $p1, "/events"),
            concat!("/orgs/", $p1, "/hooks"),
            concat!("/orgs/", $p1, "/hooks/", $p2),
            concat!("/orgs/", $p1, "/hooks/", $p2, "/pings"),
            concat!("/orgs/", $p1, "/installation"),
            concat!("/orgs/", $p1, "/interaction-limits"),
            concat!("/orgs/", $p1, "/invitations"),
            concat!("/orgs/", $p1, "/invitations/", $p2, "/teams"),
            concat!("/orgs/", $p1, "/issues"),
            concat!("/orgs/", $p1, "/members"),
            concat!("/orgs/", $p1, "/members/", $p2),
            concat!("/orgs/", $p1, "/memberships/", $p2),
            concat!("/orgs/", $p1, "/migrations"),
            concat!("/orgs/", $p1, "/migrations/", $p2),
            concat!("/orgs/", $p1, "/migrations/", $p2, "/archive"),
            concat!("/orgs/", $p1, "/migrations/", $p2, "/repos/", $p3, "/lock"),
            concat!("/orgs/", $p1, "/outside_collaborators"),
            concat!("/orgs/", $p1, "/outside_collaborators/", $p2),
            concat!("/orgs/", $p1, "/projects"),
            concat!("/orgs/", $p1, "/public_members"),
            concat!("/orgs/", $p1, "/public_members/", $p2),
            concat!("/orgs/", $p1, "/repos"),
            concat!("/orgs/", $p1, "/teams"),
            concat!("/projects/", $p1),
            concat!("/projects/", $p1, "/collaborators"),
            concat!("/projects/", $p1, "/collaborators/", $p2),
            concat!("/projects/", $p1, "/collaborators/", $p2, "/permission"),
            concat!("/projects/", $p1, "/columns"),
            concat!("/projects/columns/cards/", $p1),
            concat!("/projects/columns/cards/", $p1, "/moves"),
            concat!("/projects/columns/", $p1),
            concat!("/projects/columns/", $p1, "/cards"),
            concat!("/projects/columns/", $p1, "/moves"),
            concat!("/rate_limit"),
            concat!("/reactions/", $p1),
            concat!("/repos/", $p1, "/", $p2),
            concat!("/repos/", $p1, "/", $p2, "/assignees"),
            concat!("/repos/", $p1, "/", $p2, "/assignees/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/branches"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/enforce_admins"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/required_pull_request_reviews"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/required_signatures"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/required_status_checks"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/required_status_checks/contexts"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/restrictions"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/restrictions/teams"),
            concat!("/repos/", $p1, "/", $p2, "/branches/", $p3, "/protection/restrictions/users"),
            concat!("/repos/", $p1, "/", $p2, "/check-runs"),
            concat!("/repos/", $p1, "/", $p2, "/check-runs/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/check-runs/", $p3, "/annotations"),
            concat!("/repos/", $p1, "/", $p2, "/check-suites"),
            concat!("/repos/", $p1, "/", $p2, "/check-suites/preferences"),
            concat!("/repos/", $p1, "/", $p2, "/check-suites/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/check-suites/", $p3, "/check-runs"),
            concat!("/repos/", $p1, "/", $p2, "/check-suites/", $p3, "/rerequest"),
            concat!("/repos/", $p1, "/", $p2, "/collaborators"),
            concat!("/repos/", $p1, "/", $p2, "/collaborators/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/collaborators/", $p3, "/permission"),
            concat!("/repos/", $p1, "/", $p2, "/comments"),
            concat!("/repos/", $p1, "/", $p2, "/comments/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/comments/", $p3, "/reactions"),
            concat!("/repos/", $p1, "/", $p2, "/commits"),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3, "/check-runs"),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3, "/check-suites"),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3, "/comments"),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3, "/status"),
            concat!("/repos/", $p1, "/", $p2, "/commits/", $p3, "/statuses"),
            // "/repos/:owner/:repo/commits/:sha",
            // "/repos/:owner/:repo/commits/:sha/comments",
            concat!("/repos/", $p1, "/", $p2, "/community/code_of_conduct"),
            concat!("/repos/", $p1, "/", $p2, "/community/profile"),
            // "/repos/:owner/:repo/compare/:base...:head",
            concat!("/repos/", $p1, "/", $p2, "/contents/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/contributors"),
            concat!("/repos/", $p1, "/", $p2, "/deployments"),
            concat!("/repos/", $p1, "/", $p2, "/deployments/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/deployments/", $p3, "/statuses"),
            concat!("/repos/", $p1, "/", $p2, "/deployments/", $p3, "/statuses/", $p4),
            concat!("/repos/", $p1, "/", $p2, "/downloads"),
            concat!("/repos/", $p1, "/", $p2, "/downloads/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/events"),
            concat!("/repos/", $p1, "/", $p2, "/forks"),
            concat!("/repos/", $p1, "/", $p2, "/git/blobs"),
            concat!("/repos/", $p1, "/", $p2, "/git/blobs/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/git/commits"),
            concat!("/repos/", $p1, "/", $p2, "/git/commits/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/git/refs"),
            // "/repos/:owner/:repo/git/refs/:namespace",
            concat!("/repos/", $p1, "/", $p2, "/git/refs/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/git/tags"),
            concat!("/repos/", $p1, "/", $p2, "/git/tags/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/git/trees"),
            concat!("/repos/", $p1, "/", $p2, "/git/trees/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/hooks"),
            concat!("/repos/", $p1, "/", $p2, "/hooks/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/hooks/", $p3, "/pings"),
            concat!("/repos/", $p1, "/", $p2, "/hooks/", $p3, "/tests"),
            concat!("/repos/", $p1, "/", $p2, "/import"),
            concat!("/repos/", $p1, "/", $p2, "/import/authors"),
            concat!("/repos/", $p1, "/", $p2, "/import/authors/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/import/large_files"),
            concat!("/repos/", $p1, "/", $p2, "/import/lfs"),
            concat!("/repos/", $p1, "/", $p2, "/installation"),
            concat!("/repos/", $p1, "/", $p2, "/interaction-limits"),
            concat!("/repos/", $p1, "/", $p2, "/invitations"),
            concat!("/repos/", $p1, "/", $p2, "/invitations/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/issues"),
            concat!("/repos/", $p1, "/", $p2, "/issues/comments"),
            concat!("/repos/", $p1, "/", $p2, "/issues/comments/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/issues/comments/", $p3, "/reactions"),
            concat!("/repos/", $p1, "/", $p2, "/issues/events"),
            concat!("/repos/", $p1, "/", $p2, "/issues/events/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/assignees"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/comments"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/events"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/labels"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/labels/", $p4),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/lock"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/reactions"),
            concat!("/repos/", $p1, "/", $p2, "/issues/", $p3, "/timeline"),
            concat!("/repos/", $p1, "/", $p2, "/keys"),
            concat!("/repos/", $p1, "/", $p2, "/keys/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/labels"),
            //   "/repos/:owner/:repo/labels/:current_name",
            concat!("/repos/", $p1, "/", $p2, "/labels/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/languages"),
            concat!("/repos/", $p1, "/", $p2, "/license"),
            concat!("/repos/", $p1, "/", $p2, "/merges"),
            concat!("/repos/", $p1, "/", $p2, "/milestones"),
            concat!("/repos/", $p1, "/", $p2, "/milestones/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/milestones/", $p3, "/labels"),
            concat!("/repos/", $p1, "/", $p2, "/notifications"),
            concat!("/repos/", $p1, "/", $p2, "/pages"),
            concat!("/repos/", $p1, "/", $p2, "/pages/builds"),
            concat!("/repos/", $p1, "/", $p2, "/pages/builds/latest"),
            concat!("/repos/", $p1, "/", $p2, "/pages/builds/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/projects"),
            concat!("/repos/", $p1, "/", $p2, "/pulls"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/comments"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/comments/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/pulls/comments/", $p3, "/reactions"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/comments"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/commits"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/files"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/merge"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/requested_reviewers"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/reviews"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/reviews/", $p4),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/reviews/", $p4, "/comments"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/reviews/", $p4, "/dismissals"),
            concat!("/repos/", $p1, "/", $p2, "/pulls/", $p3, "/reviews/", $p4, "/events"),
            concat!("/repos/", $p1, "/", $p2, "/readme"),
            concat!("/repos/", $p1, "/", $p2, "/releases"),
            concat!("/repos/", $p1, "/", $p2, "/releases/assets/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/releases/latest"),
            concat!("/repos/", $p1, "/", $p2, "/releases/tags/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/releases/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/releases/", $p3, "/assets"),
            concat!("/repos/", $p1, "/", $p2, "/stargazers"),
            concat!("/repos/", $p1, "/", $p2, "/stats/code_frequency"),
            concat!("/repos/", $p1, "/", $p2, "/stats/commit_activity"),
            concat!("/repos/", $p1, "/", $p2, "/stats/contributors"),
            concat!("/repos/", $p1, "/", $p2, "/stats/participation"),
            concat!("/repos/", $p1, "/", $p2, "/stats/punch_card"),
            concat!("/repos/", $p1, "/", $p2, "/statuses/", $p3),
            concat!("/repos/", $p1, "/", $p2, "/subscribers"),
            concat!("/repos/", $p1, "/", $p2, "/subscription"),
            concat!("/repos/", $p1, "/", $p2, "/tags"),
            concat!("/repos/", $p1, "/", $p2, "/teams"),
            concat!("/repos/", $p1, "/", $p2, "/topics"),
            concat!("/repos/", $p1, "/", $p2, "/traffic/clones"),
            concat!("/repos/", $p1, "/", $p2, "/traffic/popular/paths"),
            concat!("/repos/", $p1, "/", $p2, "/traffic/popular/referrers"),
            concat!("/repos/", $p1, "/", $p2, "/traffic/views"),
            concat!("/repos/", $p1, "/", $p2, "/transfer"),
            concat!("/repos/", $p1, "/", $p2, "/", $p3, "/", $p4),
            concat!("/repositories"),
            concat!("/scim/v2/organizations/", $p1, "/Users"),
            concat!("/scim/v2/organizations/", $p1, "/Users/", $p2),
            concat!("/search/code"),
            concat!("/search/commits"),
            concat!("/search/issues"),
            concat!("/search/labels"),
            concat!("/search/repositories"),
            concat!("/search/topics"),
            concat!("/search/users"),
            concat!("/teams/", $p1),
            concat!("/teams/", $p1, "/discussions"),
            concat!("/teams/", $p1, "/discussions/", $p2),
            concat!("/teams/", $p1, "/discussions/", $p2, "/comments"),
            concat!("/teams/", $p1, "/discussions/", $p2, "/comments/", $p3),
            concat!("/teams/", $p1, "/discussions/", $p2, "/comments/", $p3, "/reactions"),
            concat!("/teams/", $p1, "/discussions/", $p2, "/reactions"),
            concat!("/teams/", $p1, "/invitations"),
            concat!("/teams/", $p1, "/members"),
            concat!("/teams/", $p1, "/members/", $p2),
            concat!("/teams/", $p1, "/memberships/", $p2),
            concat!("/teams/", $p1, "/projects"),
            concat!("/teams/", $p1, "/projects/", $p2),
            concat!("/teams/", $p1, "/repos"),
            concat!("/teams/", $p1, "/repos/", $p2, "/", $p3),
            concat!("/teams/", $p1, "/teams"),
            concat!("/user"),
            concat!("/user/blocks"),
            concat!("/user/blocks/", $p1),
            concat!("/user/email/visibility"),
            concat!("/user/emails"),
            concat!("/user/followers"),
            concat!("/user/following"),
            concat!("/user/following/", $p1),
            concat!("/user/gpg_keys"),
            concat!("/user/gpg_keys/", $p1),
            concat!("/user/installations"),
            concat!("/user/installations/", $p1, "/repositories"),
            concat!("/user/installations/", $p1, "/repositories/", $p2),
            concat!("/user/issues"),
            concat!("/user/keys"),
            concat!("/user/keys/", $p1),
            concat!("/user/marketplace_purchases"),
            concat!("/user/marketplace_purchases/stubbed"),
            concat!("/user/memberships/orgs"),
            concat!("/user/memberships/orgs/", $p1),
            concat!("/user/migrations"),
            concat!("/user/migrations/", $p1),
            concat!("/user/migrations/", $p1, "/archive"),
            concat!("/user/migrations/", $p1, "/repos/", $p2, "/lock"),
            concat!("/user/orgs"),
            concat!("/user/projects"),
            concat!("/user/public_emails"),
            concat!("/user/repos"),
            concat!("/user/repository_invitations"),
            concat!("/user/repository_invitations/", $p1),
            concat!("/user/starred"),
            concat!("/user/starred/", $p1, "/", $p2),
            concat!("/user/subscriptions"),
            concat!("/user/subscriptions/", $p1, "/", $p2),
            concat!("/user/teams"),
            concat!("/users"),
            concat!("/users/", $p1),
            concat!("/users/", $p1, "/events"),
            concat!("/users/", $p1, "/events/orgs/", $p2),
            concat!("/users/", $p1, "/events/public"),
            concat!("/users/", $p1, "/followers"),
            concat!("/users/", $p1, "/following"),
            concat!("/users/", $p1, "/following/", $p2),
            concat!("/users/", $p1, "/gists"),
            concat!("/users/", $p1, "/gpg_keys"),
            concat!("/users/", $p1, "/hovercard"),
            concat!("/users/", $p1, "/installation"),
            concat!("/users/", $p1, "/keys"),
            concat!("/users/", $p1, "/orgs"),
            concat!("/users/", $p1, "/projects"),
            concat!("/users/", $p1, "/received_events"),
            concat!("/users/", $p1, "/received_events/public"),
            concat!("/users/", $p1, "/repos"),
            concat!("/users/", $p1, "/starred"),
            concat!("/users/", $p1, "/subscriptions"),
            concat!("/", $p1),
        ]
    }};
}
