name: codspeed

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: "1.66.0"

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed@2.6.0

      - name: Build benchmarks
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: "${{ secrets.CODSPEED_TOKEN }}"
