name: codspeed

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  SCCACHE_GHA_ENABLED: "true"

defaults:
  run:
    shell: nix develop --command bash {0}

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Configure SCCache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

      - name: Initialize Nix shell
        run: nix develop

      - name: Build benchmarks
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CathalMullan/action@main
        with:
          shell: nix develop --command bash {0}
          run: cargo codspeed run
          token: "${{ secrets.CODSPEED_TOKEN }}"

      - name: Show SCCache stats
        if: always()
        run: sccache --show-stats
