name: coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_GHA_VERSION: "1"

jobs:
  coverage:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: nix develop .#coverage --command bash {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Configure SCCache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

      - name: Initialize Nix shell
        run: nix develop .#coverage

      - name: Generate coverage
        run: cargo llvm-cov --doctests --codecov --output-path codecov.json

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: codecov.json
          fail_ci_if_error: true
          token: "${{ secrets.CODECOV_TOKEN }}"

      - name: Show SCCache stats
        if: always() && !cancelled()
        run: sccache --show-stats
