name: coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    paths:
      - "**/*.rs"

permissions:
  contents: read
  id-token: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_GHA_VERSION: "1"

jobs:
  coverage:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix develop .#coverage --command bash {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Configure SCCache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

      - name: Initialize Nix shell
        run: nix develop .#coverage

      - name: Generate coverage
        run: cargo llvm-cov nextest --codecov --output-path target/nextest/default/codecov.json

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          files: target/nextest/default/junit.xml
          fail_ci_if_error: true
          token: "${{ secrets.CODECOV_TOKEN }}"

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: target/nextest/default/codecov.json
          fail_ci_if_error: true
          token: "${{ secrets.CODECOV_TOKEN }}"

      - name: Show SCCache stats
        if: always() && !cancelled()
        run: sccache --show-stats
