name: oci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_GHA_VERSION: "1"

jobs:
  oci:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: nix develop .#oci --command bash {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Configure SCCache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);

      - name: Initialize Nix shell
        run: nix develop .#oci

      - name: Run OCI tests
        run: |
          set -eufo pipefail
          cd examples/oci
          cargo build
          cargo run &
          PID="${!}"
          sleep 3
          oci-distribution-spec-conformance
          kill "${PID}"

      - name: Upload test results to Codecov
        if: always() && !cancelled()
        uses: codecov/test-results-action@v1
        with:
          files: examples/oci/junit.xml
          fail_ci_if_error: true
          token: "${{ secrets.CODECOV_TOKEN }}"

      - name: Upload test report to GitHub
        if: always() && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: examples/oci/report.html

      - name: Show SCCache stats
        if: always() && !cancelled()
        run: sccache --show-stats
