name: Renovate

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # weekly

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # renovate
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
